# Generated by Django 2.2.4 on 2020-04-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_Exam_app', '0002_travelplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplans',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplans',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelplans',
            name='travel_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travelplans',
            name='travel_start',
            field=models.DateField(),
        ),
    ]
